const itemMetadata = {
/*General*/
"Shell Credits": { title: "Shell Credits", group: "aa", category: "general", rank: 1, image: "ww_icons/general/shell_credit.webp"},
"exp1": { title: "Resonance Potion", group: "ab", category: "general", rank: 1, image: "ww_icons/general/basic_resonance_potion.webp"},
"exp2": { title: "Resonance Potion", group: "ab", category: "general", rank: 2, image: "ww_icons/general/medium_resonance_potion.webp"},
"exp3": { title: "Resonance Potion", group: "ab", category: "general", rank: 3, image: "ww_icons/general/advanced_resonance_potion.webp"},
"exp4": { title: "Resonance Potion", group: "ab", category: "general", rank: 4, image: "ww_icons/general/premium_resonance_potion.webp"},
"expW1": { title: "Energy Core", group: "ac", category: "general", rank: 1, image: "ww_icons/general/Basic_Energy_Core.png"},
"expW2": { title: "Energy Core", group: "ac", category: "general", rank: 2, image: "ww_icons/general/Medium_Energy_Core.png"},
"expW3": { title: "Energy Core", group: "ac", category: "general", rank: 3, image: "ww_icons/general/Advanced_Energy_Core.png"},
"expW4": { title: "Energy Core", group: "ac", category: "general", rank: 4, image: "ww_icons/general/Premium_Energy_Core.png"},

/*Enemy Drops*/
"TBC_enemy": { title: "TBC Enemy", group: "b", category: "enemy", rank: 0, image: "ww_icons/skill_mat/TBC_enemy.webp"},
"LF Whisperin Core": { title: "Whisperin Core", group: "ba", category: "enemy", rank: 1, image: "ww_icons/skill_mat/lf_whisperin_core.webp"},
"MF Whisperin Core": { title: "Whisperin Core", group: "ba", category: "enemy", rank: 2, image: "ww_icons/skill_mat/mf_whisperin_core.webp"},
"HF Whisperin Core": { title: "Whisperin Core", group: "ba", category: "enemy", rank: 3, image: "ww_icons/skill_mat/hf_whisperin_core.webp"},
"FF Whisperin Core": { title: "Whisperin Core", group: "ba", category: "enemy", rank: 4, image: "ww_icons/skill_mat/ff_whisperin_core.webp"},
"LF Howler Core": { title: "Howler Core", group: "bb", category: "enemy", rank: 1, image: "ww_icons/skill_mat/lf_howler_core.webp"},
"MF Howler Core": { title: "Howler Core", group: "bb", category: "enemy", rank: 2, image: "ww_icons/skill_mat/mf_howler_core.webp"},
"HF Howler Core": { title: "Howler Core", group: "bb", category: "enemy", rank: 3, image: "ww_icons/skill_mat/hf_howler_core.webp"},
"FF Howler Core": { title: "Howler Core", group: "bb", category: "enemy", rank: 4, image: "ww_icons/skill_mat/ff_howler_core.webp"},
"Crude Ring": { title: "Ring", group: "bc", category: "enemy", rank: 1, image: "ww_icons/skill_mat/crude_ring.webp"},
"Basic Ring": { title: "Ring", group: "bc", category: "enemy", rank: 2, image: "ww_icons/skill_mat/basic_ring.webp"},
"Improved Ring": { title: "Ring", group: "bc", category: "enemy", rank: 3, image: "ww_icons/skill_mat/improved_ring.webp"},
"Tailored Ring": { title: "Ring", group: "bc", category: "enemy", rank: 4, image: "ww_icons/skill_mat/tailored_ring.webp"},
"LF Polygon Core": { title: "Polygon Core", group: "bd", category: "enemy", rank: 1, image: "ww_icons/skill_mat/lf_polygon_core.webp"},
"MF Polygon Core": { title: "Polygon Core", group: "bd", category: "enemy", rank: 2, image: "ww_icons/skill_mat/mf_polygon_core.webp"},
"HF Polygon Core": { title: "Polygon Core", group: "bd", category: "enemy", rank: 3, image: "ww_icons/skill_mat/hf_polygon_core.webp"},
"FF Polygon Core": { title: "Polygon Core", group: "bd", category: "enemy", rank: 4, image: "ww_icons/skill_mat/ff_polygon_core.webp"},
"LF Tidal Residuum": { title: "Tidal Residuum", group: "be", category: "enemy", rank: 1, image: "ww_icons/skill_mat/lf_tidal_residuum.webp"},
"MF Tidal Residuum": { title: "Tidal Residuum", group: "be", category: "enemy", rank: 2, image: "ww_icons/skill_mat/mf_tidal_residuum.webp"},
"HF Tidal Residuum": { title: "Tidal Residuum", group: "be", category: "enemy", rank: 3, image: "ww_icons/skill_mat/hf_tidal_residuum.webp"},
"FF Tidal Residuum": { title: "Tidal Residuum", group: "be", category: "enemy", rank: 4, image: "ww_icons/skill_mat/ff_tidal_residuum.webp"},
"Mask of Constraint": { title: "Mask", group: "bf", category: "enemy", rank: 1, image: "ww_icons/skill_mat/mask_of_constraint.webp"},
"Mask of Erosion": { title: "Mask", group: "bf", category: "enemy", rank: 2, image: "ww_icons/skill_mat/mask_of_erosion.webp"},
"Mask of Distortion": { title: "Mask", group: "bf", category: "enemy", rank: 3, image: "ww_icons/skill_mat/mask_of_distortion.webp"},
"Mask of Insanity": { title: "Mask", group: "bf", category: "enemy", rank: 4, image: "ww_icons/skill_mat/mask_of_insanity.webp"},
"LF Exoswarm Core": { title: "Exoswarm Core", group: "bg", category: "enemy", rank: 1, image: "ww_icons/skill_mat/lf_exoswarm_core.webp"},
"MF Exoswarm Core": { title: "Exoswarm Core", group: "bg", category: "enemy", rank: 2, image: "ww_icons/skill_mat/mf_exoswarm_core.webp"},
"HF Exoswarm Core": { title: "Exoswarm Core", group: "bg", category: "enemy", rank: 3, image: "ww_icons/skill_mat/hf_exoswarm_core.webp"},
"FF Exoswarm Core": { title: "Exoswarm Core", group: "bg", category: "enemy", rank: 4, image: "ww_icons/skill_mat/ff_exoswarm_core.webp"},
"LF Mech Core": { title: "Mech Core", group: "bh", category: "enemy", rank: 1, image: "ww_icons/skill_mat/lf_mech_core.webp"},
"MF Mech Core": { title: "Mech Core", group: "bh", category: "enemy", rank: 2, image: "ww_icons/skill_mat/mf_mech_core.webp"},
"HF Mech Core": { title: "Mech Core", group: "bh", category: "enemy", rank: 3, image: "ww_icons/skill_mat/hf_mech_core.webp"},
"FF Mech Core": { title: "Mech Core", group: "bh", category: "enemy", rank: 4, image: "ww_icons/skill_mat/ff_mech_core.webp"},
"Fractured Exoswarm Pendant": { title: "Exoswarm Pendant", group: "bi", category: "enemy", rank: 1, image: "ww_icons/skill_mat/fractured_exoswarm_pendant.webp"},
"Worn Exoswarm Pendant": { title: "Exoswarm Pendant", group: "bi", category: "enemy", rank: 2, image: "ww_icons/skill_mat/worn_exoswarm_pendant.webp"},
"Chipped Exoswarm Pendant": { title: "Exoswarm Pendant", group: "bi", category: "enemy", rank: 3, image: "ww_icons/skill_mat/chipped_exoswarm_pendant.webp"},
"Intact Exoswarm Pendant": { title: "Exoswarm Pendant", group: "bi", category: "enemy", rank: 4, image: "ww_icons/skill_mat/intact_exoswarm_pendant.webp"},

/*Weekly Material*/
"TBC_weekly": { title: "TBC Weekly", group: "c", category: "weekly", rank: 3, image: "ww_icons/skill_mat/TBC_weekly.webp"},
"Monument Bell": { title: "Monument Bell", group: "ca", category: "weekly", rank: 3, image: "ww_icons/skill_mat/monumnet_bell.webp"},
"Unending Destruction": { title: "Unending Destruction", group: "cb", category: "weekly", rank: 3, image: "ww_icons/skill_mat/unending_destruction.webp"},
"Dreamless Feather": { title: "Dreamless Feather", group: "cc", category: "weekly", rank: 3, image: "ww_icons/skill_mat/dreamless_feather.webp"},
"Sentinel's Dagger": { title: "Sentinel's Dagger", group: "cd", category: "weekly", rank: 3, image: "ww_icons/skill_mat/sentinels_dagger.webp"},
"The Netherworld's Stare": { title: "The Netherworld's Stare", group: "ce", category: "weekly", rank: 3, image: "ww_icons/skill_mat/the_netherworlds_stare.webp"},
"When Irises Bloom": { title: "When Irises Bloom", group: "cf", category: "weekly", rank: 3, image: "ww_icons/skill_mat/when_irises_bloom.webp"},
"Curse of the Abyss": { title: "Curse of the Abyss", group: "cg", category: "weekly", rank: 3, image: "ww_icons/skill_mat/curse_of_the_abyss.webp"},
"Gold in Memory": { title: "Gold in Memory", group: "ch", category: "weekly", rank: 3, image: "ww_icons/skill_mat/gold_in_memory.webp"},

/*Boss Material*/
"TBC_boss": { title: "TBC Boss", group: "d", category: "boss", rank: 3, image: "ww_icons/res_mat/TBC_boss.webp"},
"Strife Tacet Core": { title: "Strife Tacet Core", group: "da", category: "boss", rank: 3, image: "ww_icons/res_mat/strife_tacet_core.webp"},
"Thundering Tacet Core": { title: "Thundering Tacet Core", group: "db", category: "boss", rank: 3, image: "ww_icons/res_mat/thundering_tacet_core.webp"},
"Elegy Tacet Core": { title: "Elegy Tacet Core", group: "dc", category: "boss", rank: 3, image: "ww_icons/res_mat/elegy_tacet_core.webp"},
"Rage Tacet Core": { title: "Rage Tacet Core", group: "dd", category: "boss", rank: 3, image: "ww_icons/res_mat/rage_tacet_core.webp"},
"Roaring Rock Fist": { title: "Roaring Rock Fist", group: "de", category: "boss", rank: 3, image: "ww_icons/res_mat/roaring_rock_fist.webp"},
"Gold-Dissolving Feather": { title: "Gold-Dissolving Feather", group: "df", category: "boss", rank: 3, image: "ww_icons/res_mat/gold_dissolving_feather.webp"},
"Sound-Keeping Tacet Core": { title: "Sound-Keeping Tacet Core", group: "dg", category: "boss", rank: 3, image: "ww_icons/res_mat/sound_keeping_tacet_core.webp"},
"Group Abomination Tacet Core": { title: "Group Abomination Tacet Core", group: "dh", category: "boss", rank: 3, image: "ww_icons/res_mat/group_abomination_tacet_core.webp"},
"Hidden Thunder Tacet Core": { title: "Hidden Thunder Tacet Core", group: "di", category: "boss", rank: 3, image: "ww_icons/res_mat/hidden_thunder_tacet_core.webp"},
"Topological Confinement": { title: "Topological Confinement", group: "dj", category: "boss", rank: 3, image: "ww_icons/res_mat/topological_confinement.webp"},
"Blazing Bone": { title: "Blazing Bone", group: "dk", category: "boss", rank: 3, image: "ww_icons/res_mat/blazing_bone.webp"},
"Cleansing Conch": { title: "Cleansing Conch", group: "dl", category: "boss", rank: 3, image: "ww_icons/res_mat/cleansing_conch.webp"},
"Platinum Core": { title: "Platinum Core", group: "dm", category: "boss", rank: 3, image: "ww_icons/res_mat/platinum_core.webp"},
"Unfading Glory": { title: "Unfading Glory", group: "dn", category: "boss", rank: 3, image: "ww_icons/res_mat/unfading_glory.webp"},
"Truth in Lies": { title: "Truth in Lies", group: "do", category: "boss", rank: 3, image: "ww_icons/res_mat/truth_in_lies.webp"},
"Blighted Crown of Puppet King": { title: "Blighted Crown of Puppet King", group: "dp", category: "boss", rank: 3, image: "ww_icons/res_mat/blighted_crown_of_puppet_king.webp"},
"Abyssal Husk": { title: "Abyssal Husk", group: "dq", category: "boss", rank: 3, image: "ww_icons/res_mat/abyssal_husk.webp"},
"Suncoveter's Reach": { title: "Suncoveter's Reach", group: "dr", category: "boss", rank: 3, image: "ww_icons/res_mat/suncoveters_reach.webp"},
"Burning Judgment": { title: "Burning Judgment", group: "ds", category: "boss", rank: 3, image: "ww_icons/res_mat/burning_judgment.webp"},
"Our Choice": { title: "Our Choice", group: "dt", category: "boss", rank: 3, image: "ww_icons/res_mat/our_choice.webp"},

/*Domain Drops*/
"TBC_domain": { title: "TBC Domain", group: "e", category: "domain", rank: 0, image: "ww_icons/skill_mat/TBC_domain.webp"},
"Inert Metallic Drip": { title: "Metallic Drip", group: "ea", category: "domain", rank: 1, image: "ww_icons/skill_mat/inert_metallic_drip.webp"},
"Reactive Metallic Drip": { title: "Metallic Drip", group: "ea", category: "domain", rank: 2, image: "ww_icons/skill_mat/reactive_metallic_drip.webp"},
"Polarized Metallic Drip": { title: "Metallic Drip", group: "ea", category: "domain", rank: 3, image: "ww_icons/skill_mat/polarized_metallic_drip.webp"},
"Heterized Metallic Drip": { title: "Metallic Drip", group: "ea", category: "domain", rank: 4, image: "ww_icons/skill_mat/heterized_metallic_drip.webp"},
"Impure Phlogiston": { title: "Phlogiston", group: "eb", category: "domain", rank: 1, image: "ww_icons/skill_mat/impure_phlogiston.webp"},
"Extracted Phlogiston": { title: "Phlogiston", group: "eb", category: "domain", rank: 2, image: "ww_icons/skill_mat/extracted_phlogiston.webp"},
"Refined Phlogiston": { title: "Phlogiston", group: "eb", category: "domain", rank: 3, image: "ww_icons/skill_mat/refined_phlogiston.webp"},
"Flawless Phlogiston": { title: "Phlogiston", group: "eb", category: "domain", rank: 4, image: "ww_icons/skill_mat/flawless_phlogiston.webp"},
"Lento Helix": { title: "Helix", group: "ec", category: "domain", rank: 1, image: "ww_icons/skill_mat/lento_helix.webp"},
"Adagio Helix": { title: "Helix", group: "ec", category: "domain", rank: 2, image: "ww_icons/skill_mat/adagio_helix.webp"},
"Andante Helix": { title: "Helix", group: "ec", category: "domain", rank: 3, image: "ww_icons/skill_mat/andante_helix.webp"},
"Presto Helix": { title: "Helix", group: "ec", category: "domain", rank: 4, image: "ww_icons/skill_mat/presto_helix.webp"},
"Waveworn Residue 210": { title: "Waveworn Residue", group: "ed", category: "domain", rank: 1, image: "ww_icons/skill_mat/waveworn_residue_210.webp"},
"Waveworn Residue 226": { title: "Waveworn Residue", group: "ed", category: "domain", rank: 2, image: "ww_icons/skill_mat/waveworn_residue_226.webp"},
"Waveworn Residue 235": { title: "Waveworn Residue", group: "ed", category: "domain", rank: 3, image: "ww_icons/skill_mat/waveworn_residue_235.webp"},
"Waveworn Residue 239": { title: "Waveworn Residue", group: "ed", category: "domain", rank: 4, image: "ww_icons/skill_mat/waveworn_residue_239.webp"},
"Cadence Seed": { title: "Cadence", group: "ee", category: "domain", rank: 1, image: "ww_icons/skill_mat/cadence_seed.webp"},
"Cadence Bud": { title: "Cadence", group: "ee", category: "domain", rank: 2, image: "ww_icons/skill_mat/cadence_bud.webp"},
"Cadence Leaf": { title: "Cadence", group: "ee", category: "domain", rank: 3, image: "ww_icons/skill_mat/cadence_leaf.webp"},
"Cadence Blossom": { title: "Cadence", group: "ee", category: "domain", rank: 4, image: "ww_icons/skill_mat/cadence_blossom.webp"},
"Broken Wing Polarizer": { title: "Polarizer", group: "ef", category: "domain", rank: 1, image: "ww_icons/skill_mat/broken_wing_polarizer.webp"},
"Monowing Polarizer": { title: "Polarizer", group: "ef", category: "domain", rank: 2, image: "ww_icons/skill_mat/monowing_polarizer.webp"},
"Polywing Polarizer": { title: "Polarizer", group: "ef", category: "domain", rank: 3, image: "ww_icons/skill_mat/polywing_polarizer.webp"},
"Layered Wing Polarizer": { title: "Polarizer", group: "ef", category: "domain", rank: 4, image: "ww_icons/skill_mat/layered_wing_polarizer.webp"},
"Incomplete Combustor": { title: "Combustor", group: "eg", category: "domain", rank: 1, image: "ww_icons/skill_mat/incomplete_combustor.webp"},
"Aftertune Combustor": { title: "Combustor", group: "eg", category: "domain", rank: 2, image: "ww_icons/skill_mat/aftertune_combustor.webp"},
"Remnant Combustor": { title: "Combustor", group: "eg", category: "domain", rank: 3, image: "ww_icons/skill_mat/remnant_combustor.webp"},
"Reverb Combustor": { title: "Combustor", group: "eg", category: "domain", rank: 4, image: "ww_icons/skill_mat/reverb_combustor.webp"},
"Spliced String": { title: "String", group: "eh", category: "domain", rank: 1, image: "ww_icons/skill_mat/spliced_string.webp"},
"Broken String": { title: "String", group: "eh", category: "domain", rank: 2, image: "ww_icons/skill_mat/broken_string.webp"},
"Solidified String": { title: "String", group: "eh", category: "domain", rank: 3, image: "ww_icons/skill_mat/solidified_string.webp"},
"Melodic String": { title: "String", group: "eh", category: "domain", rank: 4, image: "ww_icons/skill_mat/melodic_string.webp"},
"LF Carved Crystal": { title: "Carved Crystal", group: "ei", category: "domain", rank: 1, image: "ww_icons/skill_mat/lf_carved_crystal.webp"},
"MF Carved Crystal": { title: "Carved Crystal", group: "ei", category: "domain", rank: 2, image: "ww_icons/skill_mat/mf_carved_crystal.webp"},
"HF Carved Crystal": { title: "Carved Crystal", group: "ei", category: "domain", rank: 3, image: "ww_icons/skill_mat/hf_carved_crystal.webp"},
"FF Carved Crystal": { title: "Carved Crystal", group: "ei", category: "domain", rank: 4, image: "ww_icons/skill_mat/ff_carved_crystal.webp"},
"LF Waveworn Shard": { title: "Waveworn Shard", group: "ej", category: "domain", rank: 1, image: "ww_icons/skill_mat/lf_waveworn_shard.webp"},
"MF Waveworn Shard": { title: "Waveworn Shard", group: "ej", category: "domain", rank: 2, image: "ww_icons/skill_mat/mf_waveworn_shard.webp"},
"HF Waveworn Shard": { title: "Waveworn Shard", group: "ej", category: "domain", rank: 3, image: "ww_icons/skill_mat/hf_waveworn_shard.webp"},
"FF Waveworn Shard": { title: "Waveworn Shard", group: "ej", category: "domain", rank: 4, image: "ww_icons/skill_mat/ff_waveworn_shard.webp"},

/*Flowers*/
"TBC_flower": { title: "TBC Flower", group: "fa", category: "flower", rank: 0, image: "ww_icons/asc_mat/TBC_flower.webp"},
"Bamboo Iris": { title: "Bamboo Iris", group: "faa", category: "flower", rank: 0, image: "ww_icons/asc_mat/bamboo_iris.webp"},
"Belle Poppy": { title: "Belle Poppy", group: "fab", category: "flower", rank: 0, image: "ww_icons/asc_mat/belle_poppy.webp"},
"Bloodleaf Viburnum": { title: "Bloodleaf Viburnum", group: "fac", category: "flower", rank: 0, image: "ww_icons/asc_mat/bloodleaf_viburnum.webp"},
"Coriolus": { title: "Coriolus", group: "fad", category: "flower", rank: 0, image: "ww_icons/asc_mat/coriolus.webp"},
"Firecracker Jewelweed": { title: "Firecracker Jewelweed", group: "fae", category: "flower", rank: 0, image: "ww_icons/asc_mat/firecracker_jewelweed.webp"},
"Golden Fleece": { title: "Golden Fleece", group: "faf", category: "flower", rank: 0, image: "ww_icons/asc_mat/golden_fleece.webp"},
"Iris": { title: "Iris", group: "fag", category: "flower", rank: 0, image: "ww_icons/asc_mat/iris.webp"},
"Lanternberry": { title: "Lanternberry", group: "fah", category: "flower", rank: 0, image: "ww_icons/asc_mat/lanternberry.webp"},
"Loong's Pearl": { title: "Loong's Pearl", group: "fai", category: "flower", rank: 0, image: "ww_icons/asc_mat/loongs_pearl.webp"},
"Nova": { title: "Nova", group: "faj", category: "flower", rank: 0, image: "ww_icons/asc_mat/nova.webp"},
"Pavo Plum": { title: "Pavo Plum", group: "fak", category: "flower", rank: 0, image: "ww_icons/asc_mat/pavo_plum.webp"},
"Pecok Flower": { title: "Pecok Flower", group: "fal", category: "flower", rank: 0, image: "ww_icons/asc_mat/pecok_flower.webp"},
"Seaside Cendrelis": { title: "Seaside Cendrelis", group: "fam", category: "flower", rank: 0, image: "ww_icons/asc_mat/seaside_cendrelis.webp"},
"Sword Acorus": { title: "Sword Acorus", group: "fan", category: "flower", rank: 0, image: "ww_icons/asc_mat/sword_acorus.webp"},
"Terraspawn Fungus": { title: "Terraspawn Fungus", group: "fao", category: "flower", rank: 0, image: "ww_icons/asc_mat/terraspawn_fungus.webp"},
"Violet Coral": { title: "Violet Coral", group: "fap", category: "flower", rank: 0, image: "ww_icons/asc_mat/violet_coral.webp"},
"Wintry Bell": { title: "Wintry Bell", group: "faq", category: "flower", rank: 0, image: "ww_icons/asc_mat/wintry_bell.webp"},
"Afterlife": { title: "Afterlife", group: "far", category: "flower", rank: 0, image: "ww_icons/asc_mat/afterlife.webp"},
"Luminous Calendula": { title: "Luminous Calendula", group: "fas", category: "flower", rank: 0, image: "ww_icons/asc_mat/luminous_calendula.webp"},
"Sliverglow Bloom": { title: "Sliverglow Bloom", group: "fat", category: "flower", rank: 0, image: "ww_icons/asc_mat/sliverglow_bloom.webp"},
"Stone Rose": { title: "Stone Rose", group: "fau", category: "flower", rank: 0, image: "ww_icons/asc_mat/stone_rose.webp"},
"Summer Flower": { title: "Summer Flower", group: "fav", category: "flower", rank: 0, image: "ww_icons/asc_mat/summer_flower.webp"},
"Rimewisp": { title: "Rimewisp", group: "faw", category: "flower", rank: 0, image: "ww_icons/asc_mat/rimewisp.webp"},
"Gemini Spore": { title: "Gemini Spore", group: "fax", category: "flower", rank: 0, image: "ww_icons/asc_mat/gemini_spore.webp"},
"Moss Amber": { title: "Moss Amber", group: "fay", category: "flower", rank: 0, image: "ww_icons/asc_mat/moss_amber.webp"},
"Edelschnee": { title: "Edelschnee", group: "faz", category: "flower", rank: 0, image: "ww_icons/asc_mat/edelschnee.webp"},
};
