const weapons = [
    //Swords
    {
name: "Blazing Brilliance",
image: "ww_icons/wpn/sword/Blazing-Brilliance.webp",
rank: 5,
wpn: "sword",
jsid: "ws005",
sort: 4,
},
{
name: "Bloodpact's Pledge",
image: "ww_icons/wpn/sword/Bloodpacts-Pledge.webp",
rank: 5,
wpn: "sword",
jsid: "ws005",
sort: 4,
},
{
name: "Defier's Thorn",
image: "ww_icons/wpn/sword/Defier-s-Thorn.webp",
rank: 5,
wpn: "sword",
jsid: "ws005",
sort: 4,
},
{
name: "Emerald of Genesis",
image: "ww_icons/wpn/sword/Emerald-of-Genesis.webp",
rank: 5,
wpn: "sword",
jsid: "ws005",
sort: 4,
},
{
name: "Laser Shearer",
image: "ww_icons/wpn/sword/Laser-Shearer.webp",
rank: 5,
wpn: "sword",
jsid: "ws015",
sort: 4,
},
{
name: "Red Spring",
image: "ww_icons/wpn/sword/Red-Spring.webp",
rank: 5,
wpn: "sword",
jsid: "ws005",
sort: 4,
},
{
name: "Unflickering Valor",
image: "ww_icons/wpn/sword/Unflickering-Valor.webp",
rank: 5,
wpn: "sword",
jsid: "ws005",
sort: 4,
},
{
name: "Commando of Conviction",
image: "ww_icons/wpn/sword/Commando-of-Conviction.webp",
rank: 4,
wpn: "sword",
jsid: "ws004",
sort: 4,
},
{
name: "Endless Collapse",
image: "ww_icons/wpn/sword/Endless-Collapse.webp",
rank: 4,
wpn: "sword",
jsid: "ws004",
sort: 4,
},
{
name: "Fables of Wisdom",
image: "ww_icons/wpn/sword/Fables-of-Wisdom.webp",
rank: 4,
wpn: "sword",
jsid: "ws004",
sort: 4,
},
{
name: "Lumingloss",
image: "ww_icons/wpn/sword/Lumingloss.webp",
rank: 4,
wpn: "sword",
jsid: "ws004",
sort: 4,
},
{
name: "Lunar Cutter",
image: "ww_icons/wpn/sword/Lunar-Cutter.webp",
rank: 4,
wpn: "sword",
jsid: "ws004",
sort: 4,
},
{
name: "Overture",
image: "ww_icons/wpn/sword/Overture.webp",
rank: 4,
wpn: "sword",
jsid: "ws004",
sort: 4,
},
{
name: "Somnoire Anchor",
image: "ww_icons/wpn/sword/Somnoire-Anchor.webp",
rank: 4,
wpn: "sword",
jsid: "ws004",
sort: 4,
},
{
name: "Sword #18",
image: "ww_icons/wpn/sword/Sword18.webp",
rank: 4,
wpn: "sword",
jsid: "ws004",
sort: 4,
},
{
name: "Guardian Sword",
image: "ww_icons/wpn/sword/Guardian-Sword.webp",
rank: 3,
wpn: "sword",
jsid: "ws003",
sort: 4,
},
{
name: "Originite: Type II",
image: "ww_icons/wpn/sword/Originite-Type-II.webp",
rank: 3,
wpn: "sword",
jsid: "ws003",
sort: 4,
},
{
name: "Sword of Night",
image: "ww_icons/wpn/sword/Sword-of-Night.webp",
rank: 3,
wpn: "sword",
jsid: "ws003",
sort: 4,
},
{
name: "Sword of Voyager",
image: "ww_icons/wpn/sword/Sword-of-Voyager.webp",
rank: 3,
wpn: "sword",
jsid: "ws003",
sort: 4,
},
{
name: "Tyro Sword",
image: "ww_icons/wpn/sword/Tyro-Sword.webp",
rank: 2,
wpn: "sword",
jsid: "ws002",
sort: 4,
},
{
name: "Training Sword",
image: "ww_icons/wpn/sword/Training-Sword.webp",
rank: 1,
wpn: "sword",
jsid: "ws001",
sort: 4,
},
{
name: "Emerald Sentence",
image: "ww_icons/wpn/sword/Emerald-Sentence.webp",
rank: 5,
wpn: "sword",
jsid: "ws005",
sort: 4,
},

//Rectifier
{
name: "Boson Astrolabe",
image: "ww_icons/wpn/rectifier/Boson-Astrolabe.webp",
rank: 5,
wpn: "rectifier",
jsid: "wr015",
sort: 1,
},
{
name: "Cosmic Ripples",
image: "ww_icons/wpn/rectifier/Cosmic-Ripples.webp",
rank: 5,
wpn: "rectifier",
jsid: "wr005",
sort: 1,
},
{
name: "Luminous Hymn",
image: "ww_icons/wpn/rectifier/Luminous-Hymn.webp",
rank: 5,
wpn: "rectifier",
jsid: "wr005",
sort: 1,
},
{
name: "Rime-Draped Sprouts",
image: "ww_icons/wpn/rectifier/Rime-Draped-Sprouts.webp",
rank: 5,
wpn: "rectifier",
jsid: "wr005",
sort: 1,
},
{
name: "Stellar Symphony",
image: "ww_icons/wpn/rectifier/Stellar-Symphony.webp",
rank: 5,
wpn: "rectifier",
jsid: "wr005",
sort: 1,
},
{
name: "Stringmaster",
image: "ww_icons/wpn/rectifier/Stringmaster.webp",
rank: 5,
wpn: "rectifier",
jsid: "wr005",
sort: 1,
},
{
name: "Whispers of Sirens",
image: "ww_icons/wpn/rectifier/Whispers-of-Sirens.webp",
rank: 5,
wpn: "rectifier",
jsid: "wr005",
sort: 1,
},
{
name: "Augment",
image: "ww_icons/wpn/rectifier/Augment.webp",
rank: 4,
wpn: "rectifier",
jsid: "wr004",
sort: 1,
},
{
name: "Call of the Abyss",
image: "ww_icons/wpn/rectifier/Call-of-the-Abyss.webp",
rank: 4,
wpn: "rectifier",
jsid: "wr004",
sort: 1,
},
{
name: "Comet Flare",
image: "ww_icons/wpn/rectifier/Comet-Flare.webp",
rank: 4,
wpn: "rectifier",
jsid: "wr004",
sort: 1,
},
{
name: "Fusion Accretion",
image: "ww_icons/wpn/rectifier/Fusion-Accretion.webp",
rank: 4,
wpn: "rectifier",
jsid: "wr004",
sort: 1,
},
{
name: "Jinzhou Keeper",
image: "ww_icons/wpn/rectifier/Jinzhou-Keeper.webp",
rank: 4,
wpn: "rectifier",
jsid: "wr004",
sort: 1,
},
{
name: "Ocean's Gift",
image: "ww_icons/wpn/rectifier/Oceans-Gift.webp",
rank: 4,
wpn: "rectifier",
jsid: "wr004",
sort: 1,
},
{
name: "Rectifier #25",
image: "ww_icons/wpn/rectifier/Rectifier25.webp",
rank: 4,
wpn: "rectifier",
jsid: "wr004",
sort: 1,
},
{
name: "Variation",
image: "ww_icons/wpn/rectifier/Variation.webp",
rank: 4,
wpn: "rectifier",
jsid: "wr004",
sort: 1,
},
{
name: "Waltz in Masquerade",
image: "ww_icons/wpn/rectifier/Waltz-in-Masquerade.webp",
rank: 4,
wpn: "rectifier",
jsid: "wr004",
sort: 1,
},
{
name: "Guardian Rectifier",
image: "ww_icons/wpn/rectifier/Guardian-Rectifier.webp",
rank: 3,
wpn: "rectifier",
jsid: "wr003",
sort: 1,
},
{
name: "Originite: Type V",
image: "ww_icons/wpn/rectifier/Originite-Type-V.webp",
rank: 3,
wpn: "rectifier",
jsid: "wr003",
sort: 1,
},
{
name: "Rectifier of Night",
image: "ww_icons/wpn/rectifier/Rectifier-of-Night.webp",
rank: 3,
wpn: "rectifier",
jsid: "wr003",
sort: 1,
},
{
name: "Rectifier of Voyager",
image: "ww_icons/wpn/rectifier/Rectifier-of-Voyager.webp",
rank: 3,
wpn: "rectifier",
jsid: "wr003",
sort: 1,
},
{
name: "Tyro Rectifier",
image: "ww_icons/wpn/rectifier/Tyro-Rectifier.webp",
rank: 2,
wpn: "rectifier",
jsid: "wr002",
sort: 1,
},
{
name: "Training Rectifier",
image: "ww_icons/wpn/rectifier/Training-Rectifier.webp",
rank: 1,
wpn: "rectifier",
jsid: "wr001",
sort: 1,
},
{
name: "Lethean Elegy",
image: "ww_icons/wpn/rectifier/lethean_elegy.webp",
rank: 5,
wpn: "rectifier",
jsid: "wr005",
sort: 1,
},

//Gauntlets
{
name: "Abyss Surges",
image: "ww_icons/wpn/gauntlets/Abyss-Surges.webp",
rank: 5,
wpn: "gauntlets",
jsid: "wg005",
sort: 2,
},
{
name: "Blazing Justice",
image: "ww_icons/wpn/gauntlets/Blazing_Justice.webp",
rank: 5,
wpn: "gauntlets",
jsid: "wg005",
sort: 2,
},
{
name: "Pulsation Bracer",
image: "ww_icons/wpn/gauntlets/Pulsation-Bracer.webp",
rank: 5,
wpn: "gauntlets",
jsid: "wg015",
sort: 2,
},
{
name: "Tragicomedy",
image: "ww_icons/wpn/gauntlets/Tragicomedy.webp",
rank: 5,
wpn: "gauntlets",
jsid: "wg005",
sort: 2,
},
{
name: "Verity's Handle",
image: "ww_icons/wpn/gauntlets/Veritys-Handle.webp",
rank: 5,
wpn: "gauntlets",
jsid: "wg005",
sort: 2,
},
{
name: "Amity Accord",
image: "ww_icons/wpn/gauntlets/Amity-Accord.webp",
rank: 4,
wpn: "gauntlets",
jsid: "wg004",
sort: 2,
},
{
name: "Celestial Spiral",
image: "ww_icons/wpn/gauntlets/Celestial-Spiral.webp",
rank: 4,
wpn: "gauntlets",
jsid: "wg004",
sort: 2,
},
{
name: "Gauntlets­#21D",
image: "ww_icons/wpn/gauntlets/Gauntlets21D.webp",
rank: 4,
wpn: "gauntlets",
jsid: "wg004",
sort: 2,
},
{
name: "Hollow Mirage",
image: "ww_icons/wpn/gauntlets/Hollow-Mirage.webp",
rank: 4,
wpn: "gauntlets",
jsid: "wg004",
sort: 2,
},
{
name: "Legend of Drunken Hero",
image: "ww_icons/wpn/gauntlets/Legend_of_Drunken_Hero.webp",
rank: 4,
wpn: "gauntlets",
jsid: "wg004",
sort: 2,
},
{
name: "Marcato",
image: "ww_icons/wpn/gauntlets/Marcato.webp",
rank: 4,
wpn: "gauntlets",
jsid: "wg004",
sort: 2,
},
{
name: "Stonard",
image: "ww_icons/wpn/gauntlets/Stonard.webp",
rank: 4,
wpn: "gauntlets",
jsid: "wg004",
sort: 2,
},
{
name: "Gauntlets of Night",
image: "ww_icons/wpn/gauntlets/Gauntlets-of-Night.webp",
rank: 3,
wpn: "gauntlets",
jsid: "wg003",
sort: 2,
},
{
name: "Gauntlets of Voyager",
image: "ww_icons/wpn/gauntlets/Gauntlets-of-Voyager.webp",
rank: 3,
wpn: "gauntlets",
jsid: "wg003",
sort: 2,
},
{
name: "Guardian Gauntlets",
image: "ww_icons/wpn/gauntlets/Guardian-Gauntlets.webp",
rank: 3,
wpn: "gauntlets",
jsid: "wg003",
sort: 2,
},
{
name: "Originite: Type IV",
image: "ww_icons/wpn/gauntlets/Originite-Type-IV.webp",
rank: 3,
wpn: "gauntlets",
jsid: "wg003",
sort: 2,
},
{
name: "Tyro Gauntlets",
image: "ww_icons/wpn/gauntlets/Tyro-Gauntlets.webp",
rank: 2,
wpn: "gauntlets",
jsid: "wg002",
sort: 2,
},
{
name: "Training Gauntlets",
image: "ww_icons/wpn/gauntlets/Training-Gauntlets.webp",
rank: 1,
wpn: "gauntlets",
jsid: "wg001",
sort: 2,
},
{
name: "Moongazer's Sigil",
image: "ww_icons/wpn/gauntlets/Moongazers-Sigil.webp",
rank: 5,
wpn: "gauntlets",
jsid: "wg005",
sort: 2,
},

//Pistols
{
name: "Phasic Homogenizer",
image: "ww_icons/wpn/pistols/Phasic-Homogenizer.webp",
rank: 5,
wpn: "pistols",
jsid: "wp015",
sort: 3,
},
{
name: "Spectrum Blaster",
image: "ww_icons/wpn/pistols/Spectrum-Blaster.webp",
rank: 5,
wpn: "pistols",
jsid: "wp015",
sort: 3,
},
{
name: "Static Mist",
image: "ww_icons/wpn/pistols/Static-Mist.webp",
rank: 5,
wpn: "pistols",
jsid: "wp005",
sort: 3,
},
{
name: "The Last Dance",
image: "ww_icons/wpn/pistols/The-Last-Dance.webp",
rank: 5,
wpn: "pistols",
jsid: "wp005",
sort: 3,
},
{
name: "Woodland Aria",
image: "ww_icons/wpn/pistols/Woodland-Aria.webp",
rank: 5,
wpn: "pistols",
jsid: "wp005",
sort: 3,
},
{
name: "Cadenza",
image: "ww_icons/wpn/pistols/Cadenza.webp",
rank: 4,
wpn: "pistols",
jsid: "wp004",
sort: 3,
},
{
name: "Novaburst",
image: "ww_icons/wpn/pistols/Novaburst.webp",
rank: 4,
wpn: "pistols",
jsid: "wp004",
sort: 3,
},
{
name: "Pistols #26",
image: "ww_icons/wpn/pistols/Pistols26.webp",
rank: 4,
wpn: "pistols",
jsid: "wp004",
sort: 3,
},
{
name: "Relativistic Jet",
image: "ww_icons/wpn/pistols/Relativistic-Jet.webp",
rank: 4,
wpn: "pistols",
jsid: "wp004",
sort: 3,
},
{
name: "Romance in Farewell",
image: "ww_icons/wpn/pistols/Romance_in_Farewell.webp",
rank: 4,
wpn: "pistols",
jsid: "wp004",
sort: 3,
},
{
name: "Thunderbolt",
image: "ww_icons/wpn/pistols/Thunderbolt.webp",
rank: 4,
wpn: "pistols",
jsid: "wp004",
sort: 3,
},
{
name: "Undying Flame",
image: "ww_icons/wpn/pistols/Undying-Flame.webp",
rank: 4,
wpn: "pistols",
jsid: "wp004",
sort: 3,
},
{
name: "Guardian Pistols",
image: "ww_icons/wpn/pistols/Guardian-Pistols.webp",
rank: 3,
wpn: "pistols",
jsid: "wp003",
sort: 3,
},
{
name: "Originite: Type III",
image: "ww_icons/wpn/pistols/Originite-Type-III.webp",
rank: 3,
wpn: "pistols",
jsid: "wp003",
sort: 3,
},
{
name: "Pistols of Night",
image: "ww_icons/wpn/pistols/Pistols-of-Night.webp",
rank: 3,
wpn: "pistols",
jsid: "wp003",
sort: 3,
},
{
name: "Pistols of Voyager",
image: "ww_icons/wpn/pistols/Pistols-of-Voyager.webp",
rank: 3,
wpn: "pistols",
jsid: "wp003",
sort: 3,
},
{
name: "Tyro Pistols",
image: "ww_icons/wpn/pistols/Tyro-Pistols.webp",
rank: 2,
wpn: "pistols",
jsid: "wp002",
sort: 3,
},
{
name: "Training Pistols",
image: "ww_icons/wpn/pistols/Training-Pistols.webp",
rank: 1,
wpn: "pistols",
jsid: "wp001",
sort: 3,
},
{
name: "Lux & Umbra",
image: "ww_icons/wpn/pistols/Lux-Umbra.webp",
rank: 5,
wpn: "pistols",
jsid: "wp005",
sort: 3,
},

//Broadblade
{
name: "Ages of Harvest",
image: "ww_icons/wpn/broadblade/Ages-of-Harvest.webp",
rank: 5,
wpn: "broadblade",
jsid: "wb005",
sort: 5,
},
{
name: "Lustrous Razor",
image: "ww_icons/wpn/broadblade/Lustrous_Razor.webp",
rank: 5,
wpn: "broadblade",
jsid: "wb005",
sort: 5,
},
{
name: "Radiance Cleaver",
image: "ww_icons/wpn/broadblade/Radiance-Cleaver.webp",
rank: 5,
wpn: "broadblade",
jsid: "wb015",
sort: 5,
},
{
name: "Starfield Calibrator",
image: "ww_icons/wpn/broadblade/Starfield-Calibrator.webp",
rank: 5,
wpn: "broadblade",
jsid: "wb015",
sort: 5,
},
{
name: "Verdant Summit",
image: "ww_icons/wpn/broadblade/Verdant-Summit.webp",
rank: 5,
wpn: "broadblade",
jsid: "wb005",
sort: 5,
},
{
name: "Wildfire Mark",
image: "ww_icons/wpn/broadblade/Wildfire-Mark.webp",
rank: 5,
wpn: "broadblade",
jsid: "wb005",
sort: 5,
},
{
name: "Autumntrace",
image: "ww_icons/wpn/broadblade/Autumntrace.webp",
rank: 4,
wpn: "broadblade",
jsid: "wb004",
sort: 5,
},
{
name: "Broadblade #41",
image: "ww_icons/wpn/broadblade/Broadblade41.webp",
rank: 4,
wpn: "broadblade",
jsid: "wb004",
sort: 5,
},
{
name: "Dauntless Evernight",
image: "ww_icons/wpn/broadblade/Dauntless-Evernight.webp",
rank: 4,
wpn: "broadblade",
jsid: "wb004",
sort: 5,
},
{
name: "Discord",
image: "ww_icons/wpn/broadblade/Discord.webp",
rank: 4,
wpn: "broadblade",
jsid: "wb004",
sort: 5,
},
{
name: "Helios Cleaver",
image: "ww_icons/wpn/broadblade/Helios-Cleaver.webp",
rank: 4,
wpn: "broadblade",
jsid: "wb004",
sort: 5,
},
{
name: "Meditations on Mercy",
image: "ww_icons/wpn/broadblade/Meditations-on-Mercy.webp",
rank: 4,
wpn: "broadblade",
jsid: "wb004",
sort: 5,
},
{
name: "Waning Redshift",
image: "ww_icons/wpn/broadblade/Waning-Redshif.webp",
rank: 4,
wpn: "broadblade",
jsid: "wb004",
sort: 5,
},
{
name: "Beguiling Melody",
image: "ww_icons/wpn/broadblade/Beguiling-Melody.webp",
rank: 3,
wpn: "broadblade",
jsid: "wb003",
sort: 5,
},
{
name: "Broadblade of Night",
image: "ww_icons/wpn/broadblade/Broadblade-of-Night.webp",
rank: 3,
wpn: "broadblade",
jsid: "wb003",
sort: 5,
},
{
name: "Broadblade of Voyager",
image: "ww_icons/wpn/broadblade/Broadblade-of-Voyager.webp",
rank: 3,
wpn: "broadblade",
jsid: "wb003",
sort: 5,
},
{
name: "Guardian Broadblade",
image: "ww_icons/wpn/broadblade/Guardian-Broadblade.webp",
rank: 3,
wpn: "broadblade",
jsid: "wb003",
sort: 5,
},
{
name: "Originite: Type I",
image: "ww_icons/wpn/broadblade/Originite-Type-I.webp",
rank: 3,
wpn: "broadblade",
jsid: "wb003",
sort: 5,
},
{
name: "Tyro Broadblade",
image: "ww_icons/wpn/broadblade/Tyro-Broadblade.webp",
rank: 2,
wpn: "broadblade",
jsid: "wb002",
sort: 5,
},
{
name: "Training Broadblade",
image: "ww_icons/wpn/broadblade/Training-Broadblade.webp",
rank: 1,
wpn: "broadblade",
jsid: "wb001",
sort: 5,
},
{
name: "Thunderflare Dominion",
image: "ww_icons/wpn/broadblade/Thunderflare-Dominion.webp",
rank: 5,
wpn: "broadblade",
jsid: "wb005",
sort: 5,
},
];
